DROP DATABASE IF EXISTS courseDB;
CREATE DATABASE IF NOT EXISTS courseDB;

USE courseDB;

CREATE TABLE IF NOT EXISTS Course();
CREATE TABLE IF NOT EXISTS Staff();
CREATE TABLE IF NOT EXISTS Users();
CREATE TABLE IF NOT EXISTS Attendance();
CREATE TABLE IF NOT EXISTS AttendanceInfo();